### ISSUE TITLE
Syntax Error while running in Linux with Python 2.7.x

### ISSUE THREAD

**Issue by lagru** [lagru/Vivaldi-Thumbs-Replacer#3]
Original message from @feren in issue #1 :

> @lagru , just tried it in Linux, and I'm now getting this error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/vivaldiconfigurations/Downloads/Vivaldi-Thumbs-Replacer-master/vivaldiThumbsReplacer.py", line 110, in <module>
>     main()
>   File "/home/vivaldiconfigurations/Downloads/Vivaldi-Thumbs-Replacer-master/vivaldiThumbsReplacer.py", line 79, in main
>     input("\nWARNING: Please make sure that Vivaldi isn't running. Press 'Enter' to continue.")
>   File "<string>", line 0
> 
>     ^
> SyntaxError: unexpected EOF while parsing
> ```
> 
> Any advice?
> 
> BTW, here's my paths:
> 
> ```
> # PATHs - edit only these!
> # --------------------------------------------------------------------------- #
> topSites_path = '/home/vivaldiconfigurations/.config/vivaldi/Default/Top Sites'
> bookmark_path = '/home/vivaldiconfigurations/.config/vivaldi/Default/Bookmarks'
> 
> backup_path = '/home/vivaldiconfigurations/Desktop/Backups'
> customThumbs_path = '/home/vivaldiconfigurations/Desktop/Custom Thumbnails'
> # --------------------------------------------------------------------------- #
> ```

**Comment by lagru** [comment]
Can you describe the Error a little bit more? 
- Does it happen directly after running the script or after pressing "Enter" (after the promt `WARNING: Please make sure that Vivaldi isn't running. Press 'Enter' to continue.`)? It looks like the Error happens while parsing the script.
- Which Python version do you use on Linux?

**Comment by dominichayesferen** [comment]
@lagru 
1. Yes
2. Python 2.7.12

**Comment by lagru** [comment]
Well then it's clear. You're using Python 2.7.x while this script was written for Python 3.x ([Dependencies](https://github.com/cuiba/Vivaldi-Thumbs-Replacer#dependencies)) . Especially the `input` and `print`-functions aren't compatible / the same between this versions. You get the syntax error because the `print()`-function is no valid syntax for Python 2.7.x.

If you really want to try using it with Python 2.7.x you'll have to change `print("something")` to `print "something"`. If you want to know more I recommend checking out [this](http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html#the-print-function) site.
However I can't promise that something else won't break.

**My recommendation:** Use Python 3.5 or newer!

**Comment by dominichayesferen** [comment]
@lagru 
Oops, anyway, thanks for the tip though... (Thought Ubuntu 16.04 would have Python 3... :/)

**Comment by dominichayesferen** [comment]
@lagru 
Hmm, odd, just looked and Python 3 is there as the command 'python3' but your script seems to be pointing to the Python 2.7.X files instead on my installation, weird...

**Comment by dominichayesferen** [comment]
Moved that python directory bug to the issue above, so you might want to close this one...
