### ISSUE TITLE
Wont work for multiple speed dial folders or if speed dial is not the first folder in Bookmarks file

### ISSUE THREAD

**Issue by cB-Abhinav-Gautam** [lagru/Vivaldi-Thumbs-Replacer#5]
Wont work for multiple speed dial folders or if speed dial is not the first folder in Bookmarks file.
Also will fail for folder inside folder
Also new speed dials will not be updated without adding 'meta_info' tag in each entry. Please check 
https://github.com/Gotham13121997/Vivaldi-SpeedDial-Thumbnail-Fetcher and update the code. 👍

**Comment by lagru** [comment]
Hey, thank you for your feedback and time.

I'll have a look but I'm not promising anything as this project was a solution to a problem I only had with Vivaldi until version 1.10 (see Note in Readme). After 1.10 one could add thumbnails more easily by hand.

In any case I will either update the script or indicate more clearly that this project does not longer work with the newest versions in the next few days. Of course I would accept a pull request as well.
